name: elkollege_schedule_app
description: "Приложение для просмотра актуального расписания ЭК"
repository: https://github.com/diquoks/ElkollegeScheduleApp
publish_to: none
version: 1.0.0-dev

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  go_router: ^18.0.1
  shared_preferences: ^2.5.5
  web: ^1.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
